install.packages("arules")
install.packages("class", dependencies = TRUE)
install.packages("caret", dependencies = TRUE)
install.packages("dplyr", dependencies = TRUE)
install.packages("e1071", dependencies = TRUE)
install.packages("FNN", dependencies = TRUE)
install.packages("gmodels", dependencies = TRUE)
install.packages("psych", dependencies = TRUE)
install.packages("data.table", dependencies=TRUE)
install.packages("BiocManager", dependecies=)